### ISSUE TITLE
Implement recording events to the database

### ISSUE THREAD

**Issue by MargoTuleninova** [containerum/kube-events#9]

**Comment by xakep666** [comment]
https://github.com/containerum/kube-events/commit/a07ff8e8bfa6740392df82245932eead3d42c9e2
https://github.com/containerum/kube-events/commit/75c8796f6f356a78eeb2649de0b0548f82ff192d
https://github.com/containerum/kube-events/commit/ac20e73785c3d131fd88551a60fa4e102d99060d
